name: ✨ Feature Request
description: Suggest an idea / enhancement
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What problem are we trying to solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: What do you want to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
  - type: textarea
    attributes:
      label: Additional context
